# Dùng bộ gốc có sẵn playwright và mọi thư viện hệ điều hành
FROM mcr.microsoft.com/playwright/python:v1.49.0-jammy

WORKDIR /app

# Cài đặt nano và dọn dẹp bộ nhớ đệm để giảm dung lượng image
RUN apt-get update && apt-get install -y nano && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN playwright install chromium

# Copy toàn bộ code
COPY . .

# Chạy bot
CMD ["python", "crawl_bot.py"]
